AllCops:
  TargetRubyVersion: 2.6
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'spec/rails_app/**/*'
    - 'spec/spec_helper.rb'
    - 'vendor/bundle/**/*'
  SuggestExtensions: false
  NewCops: enable
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SignalException:
  Enabled: false
Layout/LineLength:
  Max: 100
Gemspec/OrderedDependencies:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/MethodLength:
  Max: 15
