AllCops:
  TargetRubyVersion: 2.5
  Include:
    - 'lib'
    - 'spec'
  Exclude:
    - 'spec/rails_app/**/*'
    - 'spec/spec_helper.rb'
    - 'vendor/bundle/**/*'
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SignalException:
  Enabled: false
Metrics/LineLength:
  Max: 100
Gemspec/OrderedDependencies:
  Enabled: false
Naming/FileName:
  Exclude:
    - 'Rakefile'
    - 'Gemfile'
    - 'Appraisals'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/MethodLength:
  Max: 15
