name: Ruby

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - rails4.2
          - rails5.2
          - rails6.0
        ruby:
          - 2.4
          - 2.5
          - 2.6
          - 2.7
        exclude:
          - gemfile: rails6.0
            ruby: 2.4
    name: ${{ matrix.gemfile }}, ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
    - name: Run tests
      run: |
        bundle exec rake spec
